In [4]:
import numpy as np
from pyAQuN.pyAQuN import pyAQuN
M = np.random.rand(10,5)
qM, binassignments = pyAQuN.normalize(M)
qM, binassignments

(array([[0.63596859, 0.12583476, 0.76466173, 0.30216966, 0.363238  ],
        [0.76466173, 0.18116841, 0.50202589, 0.18116841, 0.        ],
        [0.12583476, 0.76466173, 0.63596859, 0.71970937, 0.18116841],
        [0.18116841, 0.87689322, 0.363238  , 0.87689322, 0.71970937],
        [0.71970937, 0.50202589, 0.71970937, 0.12583476, 0.50202589],
        [0.        , 0.363238  , 0.87689322, 0.76466173, 0.76466173],
        [0.30216966, 0.63596859, 0.30216966, 0.        , 0.87689322],
        [0.363238  , 0.30216966, 0.12583476, 0.363238  , 0.30216966],
        [0.87689322, 0.        , 0.18116841, 0.63596859, 0.63596859],
        [0.50202589, 0.71970937, 0.        , 0.50202589, 0.12583476]]),
 array([[ 56,   1,  78,  23,  34],
        [ 78,  12,  45,  12, 100],
        [  1,  78,  56,  67,  12],
        [ 12,  89,  34,  89,  67],
        [ 67,  45,  67,   1,  45],
        [100,  34,  89,  78,  78],
        [ 23,  56,  23, 100,  89],
        [ 34,  23,   1,  34,  23],
        [ 89, 100,

In [24]:
from pyAQuN.pyAQuN import pyAQuN
import numpy as np

class pyAQuN:
    @staticmethod
    def normalize(M):
        M = np.random.rand(10,5)
        nans = np.isnan(M)
        jitteredM = M + np.random.rand(M.shape[0], M.shape[1]) * 0.1
        prctiles =  np.nanpercentile(jitteredM, range(0,100), axis=0)
        binassignments = np.asarray([np.digitize(x, y) for x, y in zip(jitteredM.transpose(), prctiles.transpose())]).transpose()
        qM = np.zeros(M.shape)
        for p in range(0, 100):
            inP = binassignments==p
            qM[inP] = np.nanmedian(jitteredM[inP])
        qM[nans] = np.nan



In [63]:
M = np.random.rand(10,5)
nans = np.isnan(M)
jitteredM = M + np.random.rand(M.shape[0], M.shape[1]) * 0.1
prctiles =  np.nanpercentile(jitteredM, range(0,100), axis=0)
binassignments = np.asarray([np.digitize(x, y) for x, y in zip(jitteredM.transpose(), prctiles.transpose())]).transpose()
qM = np.zeros(M.shape)
for p in range(0, 100):
    inP = binassignments==p
    qM[inP] = np.nanmedian(jitteredM[inP])
qM[nans] = np.nan


array([[0.54890299, 0.35713071, 0.15437903, 0.07748168, 0.25341377],
       [0.        , 0.20217964, 0.55702106, 0.        , 0.35713071],
       [0.68560131, 0.07748168, 0.68560131, 0.15437903, 0.55702106],
       [0.07748168, 0.15437903, 0.25341377, 0.83498419, 0.07748168],
       [0.15437903, 0.25341377, 0.20217964, 0.54890299, 0.        ],
       [0.20217964, 0.55702106, 0.54890299, 0.20217964, 0.83498419],
       [0.83498419, 0.68560131, 0.        , 0.25341377, 0.68560131],
       [0.25341377, 0.54890299, 0.07748168, 0.35713071, 0.20217964],
       [0.35713071, 0.83498419, 0.83498419, 0.68560131, 0.15437903],
       [0.55702106, 0.        , 0.35713071, 0.55702106, 0.54890299]])

In [60]:
np.nanmedian([0.1, 0.5, np.nan, 5])

0.5

In [49]:
inP=binassignments==1
qM[inP] = np.median(jitteredM[inP])

SyntaxError: can't assign to function call (<ipython-input-49-3dd3aa76ecf2>, line 2)

In [43]:
qM = np.zeros(M.shape)
qM.shape

(10, 5)

In [34]:
len(np.histogram(M))

2